version: 1
formatters:
  tsm:
      style: '{'
      format: '[{asctime}] {process} {name} {levelname:8} {message}'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: tsm
    stream: ext://sys.stderr
root:
  # level is overwritten at runtime
  level: NOTSET
  handlers: [console]